language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - '7.1'
    - '7.2'
    - '7.3'

before_script:
    - flags="-o"
    - composer install $flags

script: make travis

after_success:
    - bash <(curl -s https://codecov.io/bash)
